### ISSUE TITLE
Determine namespace for DGGS ontology

### ISSUE THREAD

**Issue by dr-shorthair** [CSIRO-enviro-informatics/dggs-ont#1]
The notional/provisional namespace used so far is `http://linked.data.gov.au/def/auspix#` with a short form prefix `apo:` 

In order to move forward in developing publishing this there would need to be a decision about 
(a) whether the `http://linked.data.gov.au/def` pattern is suitable, in which case an application must be made here http://catalogue.linked.data.gov.au/ 
(b) if this is an AusPIX ontology (suggested) or if a more general DGGS ontology is the target, which affects the local name
(c) currently this is being developed in a repo in the https://github.com/CSIRO-enviro-informatics organization; should this be moved to Geoscience Australia's GitHub organization? 

@bellie888 and @ibastrak can you comment please?

**Comment by ibastrak** [comment]
How timely :-) Shane and I just talked about it. I remembered that while we progressed namespace approval for the Place Names, I also needed to submit a similar request for the DGGS. I'll try to do it today.

**Comment by ibastrak** [comment]
I need to reread the whole comment - will respond to it after our meeting at 3 today

**Comment by ibastrak** [comment]
Hi Simon,

(a) whether the http://linked.data.gov.au/def pattern is suitable, in which case an application must be made here http://catalogue.linked.data.gov.au/ 

Agreed last week to use this pattern, I started the process of requesting a namespace for this ontology. I need an **ontology file** to finish submission

(b) if this is an AusPIX ontology (suggested) or if a more general DGGS ontology is the target, which affects the local name 

Agreed, this is the AusPIX ontology

(c) currently this is being developed in a repo in the https://github.com/CSIRO-enviro-informatics organization; should this be moved to Geoscience Australia's GitHub organization?
It would need to move to GA GitHub for future management. When would be the right time to do that?

**Comment by dr-shorthair** [comment]
Starting at the bottom: 
(c) I suggest we move it now. I just tried to transfer it but I don’t have permission to create a repo in your organization (fair enough) so you guys will have to do it

(b) I just changed all the dggs &rarr; auspix so the repo is now https://github.com/CSIRO-enviro-informatics/auspix-ont 

(a) then you will have the [ontology file](https://github.com/CSIRO-enviro-informatics/auspix-ont/blob/master/auspix.ttl). And then we will also have to set up the PID redirect.

**Comment by ibastrak** [comment]
Can you send me a copy of the file itself please as I cannot download it from the repository?
Alternatively, I can create a new file by copying the context but it may introduce some odd additions.

**Comment by dr-shorthair** [comment]
The file is at [this link](https://github.com/CSIRO-enviro-informatics/auspix-ont/blob/master/auspix.ttl) already given above. Click `[Raw]` to see it without the framing.

**Comment by ibastrak** [comment]
Yes, I was going to copy it ('raw') but decided to ask you first just in case. Will do it now.

**Comment by ibastrak** [comment]
Just submitted. Added CSIRO as creator, GA as publisher and Simon Cox as a contact person
Let me know if you wish to change anything

**Comment by dr-shorthair** [comment]
Will you transfer the repo to https://github.com/GeoscienceAustralia ?

**Comment by ibastrak** [comment]
I am going to ask Joe to do it or to see if you can have a permission to do it. Any preference?

**Comment by dr-shorthair** [comment]
It will be cleanest (and rather easy) if I could temporarily be given permission to create a repo in  https://github.com/GeoscienceAustralia - there is a standard GitHub script  https://help.github.com/en/github/administering-a-repository/transferring-a-repository

**Comment by dr-shorthair** [comment]
Transferred to https://github.com/GeoscienceAustralia/AusPIX-DGGS-ontology
