### ISSUE TITLE
Transfer repo to GA

### ISSUE THREAD

**Issue by jyucsiro** [CSIRO-enviro-informatics/dggs-ont#2]

**Comment by bellie888** [comment]
Asked Alice Lee at GA to make a repo for us - just now, it's called:
"AusPIX-DGGS-ontology" to match the naming conventions of other AusPIX repo's
Cheers
Joe 
19/5/2020

**Comment by dr-shorthair** [comment]
Dev moved to https://github.com/GeoscienceAustralia/AusPIX-DGGS-ontology
